### ISSUE TITLE
Не выдает результаты если в запросе есть слеш

### ISSUE THREAD

**Issue by SerNeo** [webber12/evoSearch#16]
здравствуйте,
Не подскажете как настроить так чтобы в запросе можно было указывать и символа "/" (например "25/50"). 
Сейчас при вводе запроса с "/" резульат очень странный. показываются только картинки а текста и краткое описание нет.

**Comment by webber12** [comment]
Есть такое дело из-за preg_replace для подсветки результатов. Попробуйте вот эту правку https://github.com/webber12/evoSearch/commit/9df9b8fd70247f6af3e93b4149548990860c37fc

**Comment by SerNeo** [comment]
помогло! 
Огромное спасибо!
