### ISSUE TITLE
"&noResult" not showing if HTML is in "&ownerTPL"

### ISSUE THREAD

**Issue by modxuser** [webber12/evoSearch#30]
There are a variety of ways to test this, numerous don't work, some do, the easiest way is:

**This works:**

Call `&noResult` like this:

```
&noResult=`<p>No results for: &quot;[+stat_request+]&quot;</p>` 
```

Now add 

```
&ownerTPL=`@CODE:[+dl.wrap+]` 
```

**This doesn't work:**

Call `&noResult` as shown above

Change `&ownerTPL` to the following:

```
&ownerTPL=`@CODE:<ul>[+dl.wrap+]</ul>`
```

The "noresults" template will no-longer be shown, simply due to adding the `<ul></ul>`

**Comment by fourroses666** [comment]
Wonder if it does work when you use a chunk for the &tpl.

``` &ownerTPL=`tpl-result` ```

`<ul>[+dl.wrap+]</ul>`

**Comment by modxuser** [comment]
> 
> 
> Wonder if it does work when you use a chunk for the &tpl.
> 
> `` &ownerTPL=`tpl-result` ``
> 
> `<ul>[+dl.wrap+]</ul>`

As already mentioned in my first post: there are a variety of ways to test

One of those was using a chunk, you can add a chunk either using `{{}}` or without, each gives a different result

The fact that the Snippet doesn't completely adhere to how Doclister is setup makes things slightly complicated, as it's a mix of code types and some work, some don't, and some work together, whereas others don't

**Comment by nick0** [comment]
> 
> 
> Wonder if it does work when you use a chunk for the &tpl.
> 
> `` &ownerTPL=`tpl-result` ``
> 
> `<ul>[+dl.wrap+]</ul>`

Confirming this bug if html is in the &ownerTPL parameter.
The bug also exists if a chunk with html in it is used for the &ownerTPL.

**Comment by argalkin** [comment]
&noneWrapOuter=`0` добавить в вызов evoSearch
а в 47-ой строчке сниппета  assets/snippets/evoSearch/evoSearch.snippet.php добавить условие:
if ($eSS->params['show_stat'] == '1' && (!empty($output))) {
                $output = $eSS->getSearchResultInfo() . $output;
            }
            
            Ну и добавить параметр &noResult=`<div>По запросу <u>[+stat_request+]</u> ничего не найдено. Смягчите условия поиска</div>`

**Comment by webber12** [comment]
&noneWrapOuter=0 + fix https://github.com/webber12/evoSearch/commit/f17370caa07961361f9f7983be02d8aa5876c11a
