### ISSUE TITLE
Mysql8: Illegal argument to a regular expression

### ISSUE THREAD

**Issue by 0test** [webber12/evoSearch#31]
При отсутствии результатов в Mysql8 получаем такую ошибку

```
« Evolution CMS Parse Error »
SQLSTATE[HY000]: General error: 3685 Illegal argument to a regular expression.
```
Ноги растут [отсюда](https://github.com/webber12/evoSearch/blob/e5c2dd6650faf8e3bf35c3774348e61023d8f236/assets/snippets/evoSearch/snippet.class.php#L395)

В восьмой версии помогла такая правка:
 `$tmp[] = " LOWER(`" . $search_field . "`) REGEXP '\\\\b(" . $word . ")\\\\b'";`

Может стоит как-то определять версию БД?
Например нашёл такое:
`$modx->db->conn->getAttribute(constant("PDO::ATTR_SERVER_VERSION"))`

**Comment by webber12** [comment]
https://github.com/webber12/evoSearch/commit/da23335488ee36713e1045958079045d3e7623bd
