### ISSUE TITLE
api=1 & show_stat

### ISSUE THREAD

**Issue by 0test** [webber12/evoSearch#37]
В режиме апи и при установленном параметре `show_stat=1` возвращает некорректный Json. Вставляет простой html  в начало выдачи.
В режиме` show_stat=0` плейсхолдеры stat_total ,stat_display, stat_from,stat_to недоступны.

**Comment by webber12** [comment]
https://github.com/webber12/evoSearch/commit/c325b7d96d9438f4f065302a0b547e83aadc5b1c
